/**
 * Name: Jugal Bilimoria
 * Date: 8/19/2018
 * Title: Linear and Quadratic Graph Helper (Final Project)
 * Purpose: To satisfy the need of my client, Mrs. Trinh's request
 *          of a program to help her students gain knowledge of
 *          graphing linear and quadratic equations. 
 */

import java.util.ArrayList; 
import java.io.*; 
public class U4_A3_Implementation extends javax.swing.JFrame {
    
    
    /**
     * Creates new form 
     */
    public U4_A3_Implementation() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main = new javax.swing.JPanel();
        btnQuadratic = new javax.swing.JButton();
        btnLinear = new javax.swing.JButton();
        lblStart = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        Quadratics = new javax.swing.JPanel();
        lblQTitle = new javax.swing.JLabel();
        btnQBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblQA = new javax.swing.JLabel();
        lblQH = new javax.swing.JLabel();
        lblQK = new javax.swing.JLabel();
        txtA = new javax.swing.JTextField();
        txtH = new javax.swing.JTextField();
        txtK = new javax.swing.JTextField();
        btnCalculate = new javax.swing.JButton();
        Linear = new javax.swing.JPanel();
        lblLTitle = new javax.swing.JLabel();
        btnLBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnLCalculate = new javax.swing.JButton();
        lblLM = new javax.swing.JLabel();
        lblLB = new javax.swing.JLabel();
        txtM = new javax.swing.JTextField();
        txtB = new javax.swing.JTextField();
        QuadraticsCalc = new javax.swing.JPanel();
        lblQCTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaQuadCalc = new javax.swing.JTextArea();
        btnQCBack = new javax.swing.JButton();
        btnQCSteps = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblQCY = new javax.swing.JLabel();
        btnQCFind = new javax.swing.JButton();
        txaQCX = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        LinearCalc = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaLineCalc = new javax.swing.JTextArea();
        btnLCBack = new javax.swing.JButton();
        btnLCSteps = new javax.swing.JButton();
        lblLCTitle = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnLCFind = new javax.swing.JButton();
        txaLCX = new javax.swing.JTextField();
        lblLCY = new javax.swing.JLabel();
        QuadraticSteps = new javax.swing.JPanel();
        lblQSTitle = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaQuadSteps = new javax.swing.JTextArea();
        btnQSBack = new javax.swing.JButton();
        LinearSteps = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txaLineSteps = new javax.swing.JTextArea();
        btnLSBack = new javax.swing.JButton();
        lblLSTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Main.setBackground(new java.awt.Color(149, 199, 242));

        btnQuadratic.setBackground(new java.awt.Color(192, 149, 242));
        btnQuadratic.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnQuadratic.setText("Quadratic > ");
        btnQuadratic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuadraticActionPerformed(evt);
            }
        });

        btnLinear.setBackground(new java.awt.Color(192, 149, 242));
        btnLinear.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnLinear.setText("< Linear");
        btnLinear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLinearActionPerformed(evt);
            }
        });

        lblStart.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblStart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStart.setText("<html>Welcome to Jugal's Linear and Quadratic "
            + "<br> graph helper. The goal of this program is to "
            + "<br>help you to further understand the concepts of "
            + "<br>graphing linear and quadratic systems. "
            + "<br>"+"<br>Please choose and option below to get started!</html>");

        lblTitle.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Linear & Quadratics Graph Helper");

        javax.swing.GroupLayout MainLayout = new javax.swing.GroupLayout(Main);
        Main.setLayout(MainLayout);
        MainLayout.setHorizontalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnLinear, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnQuadratic)
                .addGap(31, 31, 31))
            .addGroup(MainLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblStart, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MainLayout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(34, Short.MAX_VALUE)))
        );
        MainLayout.setVerticalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainLayout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addComponent(lblStart, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLinear, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuadratic, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
            .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MainLayout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(252, Short.MAX_VALUE)))
        );

        Quadratics.setBackground(new java.awt.Color(149, 199, 242));
        Quadratics.setVisible(false);

        lblQTitle.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblQTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQTitle.setText("Quadratic Graph Helper");

        btnQBack.setBackground(new java.awt.Color(192, 149, 242));
        btnQBack.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnQBack.setText("< Back");
        btnQBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQBackbtnQBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel1.setText("<html>Before starting, make sure the equation is in"
            + "<br>vertex form: y = a(x-h)<sup>2</sup>+k. You can"
            + "<br>change the operator from + to - by simply "
            + "<br>inputting the value with a - sign infront, vice "
            +"versa</html>");

        lblQA.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblQA.setText("Enter \"a\" value: ");

        lblQH.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblQH.setText("Enter \"h\" value: ");

        lblQK.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblQK.setText("Enter \"k\" value: ");

        txtA.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtA.setToolTipText("");
        txtA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAActionPerformed(evt);
            }
        });

        txtH.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtH.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtK.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtK.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnCalculate.setBackground(new java.awt.Color(192, 149, 242));
        btnCalculate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCalculate.setText("Calculate >");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout QuadraticsLayout = new javax.swing.GroupLayout(Quadratics);
        Quadratics.setLayout(QuadraticsLayout);
        QuadraticsLayout.setHorizontalGroup(
            QuadraticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuadraticsLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(QuadraticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblQH)
                    .addComponent(lblQA)
                    .addComponent(lblQK))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(QuadraticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtH, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtK, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(114, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuadraticsLayout.createSequentialGroup()
                .addGroup(QuadraticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(QuadraticsLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnQBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCalculate))
                    .addGroup(QuadraticsLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(QuadraticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblQTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE))))
                .addGap(22, 22, 22))
        );
        QuadraticsLayout.setVerticalGroup(
            QuadraticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuadraticsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(QuadraticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtA, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(lblQA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(QuadraticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQH, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(QuadraticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQK, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtK))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(QuadraticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCalculate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Linear.setBackground(new java.awt.Color(149, 199, 242));
        Linear.setVisible(false);

        lblLTitle.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblLTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLTitle.setText("Linear Graph Helper");

        btnLBack.setBackground(new java.awt.Color(192, 149, 242));
        btnLBack.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnLBack.setText("< Back");
        btnLBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLBackbtnQBackActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel2.setText("<html>Before starting, make sure the equation is in"
            + "<br>slope/y-intercept form: y = m*x+b. You can"
            + "<br>change the operator from + to - by simply "
            + "<br>inputting the value with a - sign infront,and vice "
            + "versa</html>");

        btnLCalculate.setBackground(new java.awt.Color(192, 149, 242));
        btnLCalculate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnLCalculate.setText("Calculate >");
        btnLCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLCalculateActionPerformed(evt);
            }
        });

        lblLM.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblLM.setText("Enter \"m\" value: ");

        lblLB.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblLB.setText("Enter \"b\" value: ");

        txtM.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtM.setToolTipText("");
        txtM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMActionPerformed(evt);
            }
        });

        txtB.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtB.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout LinearLayout = new javax.swing.GroupLayout(Linear);
        Linear.setLayout(LinearLayout);
        LinearLayout.setHorizontalGroup(
            LinearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LinearLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(LinearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LinearLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LinearLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(LinearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LinearLayout.createSequentialGroup()
                                .addComponent(btnLBack, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLCalculate)
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LinearLayout.createSequentialGroup()
                                .addComponent(lblLTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LinearLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(LinearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLB)
                    .addComponent(lblLM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LinearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtM, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtB, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102))
        );
        LinearLayout.setVerticalGroup(
            LinearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LinearLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(LinearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LinearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLB, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtB))
                .addGap(40, 40, 40)
                .addGroup(LinearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLCalculate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        QuadraticsCalc.setBackground(new java.awt.Color(149, 199, 242));
        QuadraticsCalc.setVisible(false);

        lblQCTitle.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblQCTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQCTitle.setText("Quadratic Graph Helper Calculation");

        txaQuadCalc.setEditable(false);
        txaQuadCalc.setColumns(20);
        txaQuadCalc.setLineWrap(true);
        txaQuadCalc.setRows(5);
        txaQuadCalc.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txaQuadCalc);

        btnQCBack.setBackground(new java.awt.Color(192, 149, 242));
        btnQCBack.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnQCBack.setText("< Back");
        btnQCBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQCBackActionPerformed(evt);
            }
        });

        btnQCSteps.setBackground(new java.awt.Color(192, 149, 242));
        btnQCSteps.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnQCSteps.setText("Steps >");
        btnQCSteps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQCStepsActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Enter x value to find y value");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Y value:");

        lblQCY.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblQCY.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnQCFind.setText("Find");
        btnQCFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQCFindActionPerformed(evt);
            }
        });

        txaQCX.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txaQCX.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("X value:");

        javax.swing.GroupLayout QuadraticsCalcLayout = new javax.swing.GroupLayout(QuadraticsCalc);
        QuadraticsCalc.setLayout(QuadraticsCalcLayout);
        QuadraticsCalcLayout.setHorizontalGroup(
            QuadraticsCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuadraticsCalcLayout.createSequentialGroup()
                .addGroup(QuadraticsCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(QuadraticsCalcLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(QuadraticsCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(QuadraticsCalcLayout.createSequentialGroup()
                                .addComponent(btnQCBack, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnQCSteps))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblQCTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)))
                    .addGroup(QuadraticsCalcLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(QuadraticsCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuadraticsCalcLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txaQCX, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnQCFind)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblQCY, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7))
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(26, 26, 26))
        );
        QuadraticsCalcLayout.setVerticalGroup(
            QuadraticsCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuadraticsCalcLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQCTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(QuadraticsCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQCY, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(QuadraticsCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnQCFind)
                        .addComponent(txaQCX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(QuadraticsCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQCBack)
                    .addComponent(btnQCSteps))
                .addContainerGap())
        );

        LinearCalc.setBackground(new java.awt.Color(149, 199, 242));
        LinearCalc.setVisible(false);

        txaLineCalc.setEditable(false);
        txaLineCalc.setColumns(20);
        txaLineCalc.setLineWrap(true);
        txaLineCalc.setRows(5);
        txaLineCalc.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txaLineCalc);

        btnLCBack.setBackground(new java.awt.Color(192, 149, 242));
        btnLCBack.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnLCBack.setText("< Back");
        btnLCBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLCBackActionPerformed(evt);
            }
        });

        btnLCSteps.setBackground(new java.awt.Color(192, 149, 242));
        btnLCSteps.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnLCSteps.setText("Steps >");
        btnLCSteps.setToolTipText("");
        btnLCSteps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLCStepsActionPerformed(evt);
            }
        });

        lblLCTitle.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblLCTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLCTitle.setText("Linear Graph Helper Calculation");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Enter x value to find y value");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("X value:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Y value:");

        btnLCFind.setText("Find");
        btnLCFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLCFindActionPerformed(evt);
            }
        });

        txaLCX.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txaLCX.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblLCY.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblLCY.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout LinearCalcLayout = new javax.swing.GroupLayout(LinearCalc);
        LinearCalc.setLayout(LinearCalcLayout);
        LinearCalcLayout.setHorizontalGroup(
            LinearCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LinearCalcLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(LinearCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LinearCalcLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txaLCX, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(btnLCFind)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLCY, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LinearCalcLayout.createSequentialGroup()
                        .addComponent(btnLCBack, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLCSteps)))
                .addGap(17, 17, 17))
            .addGroup(LinearCalcLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LinearCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLCTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        LinearCalcLayout.setVerticalGroup(
            LinearCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LinearCalcLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLCTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LinearCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLCY, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(LinearCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLCFind)
                        .addComponent(txaLCX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(LinearCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLCBack)
                    .addComponent(btnLCSteps))
                .addContainerGap())
        );

        QuadraticSteps.setBackground(new java.awt.Color(149, 199, 242));
        QuadraticSteps.setVisible(false);

        lblQSTitle.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblQSTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQSTitle.setText("Quadratic Graph Helper Steps");

        txaQuadSteps.setEditable(false);
        txaQuadSteps.setColumns(20);
        txaQuadSteps.setRows(5);
        txaQuadSteps.setWrapStyleWord(true);
        jScrollPane3.setViewportView(txaQuadSteps);

        btnQSBack.setBackground(new java.awt.Color(192, 149, 242));
        btnQSBack.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnQSBack.setText("< Back");
        btnQSBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQSBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout QuadraticStepsLayout = new javax.swing.GroupLayout(QuadraticSteps);
        QuadraticSteps.setLayout(QuadraticStepsLayout);
        QuadraticStepsLayout.setHorizontalGroup(
            QuadraticStepsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuadraticStepsLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblQSTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                .addGap(27, 27, 27))
            .addGroup(QuadraticStepsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(QuadraticStepsLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(btnQSBack, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        QuadraticStepsLayout.setVerticalGroup(
            QuadraticStepsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuadraticStepsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQSTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnQSBack)
                .addContainerGap())
        );

        LinearSteps.setBackground(new java.awt.Color(149, 199, 242));
        LinearSteps.setVisible(false);

        txaLineSteps.setEditable(false);
        txaLineSteps.setColumns(20);
        txaLineSteps.setRows(5);
        txaLineSteps.setWrapStyleWord(true);
        jScrollPane4.setViewportView(txaLineSteps);

        btnLSBack.setBackground(new java.awt.Color(192, 149, 242));
        btnLSBack.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnLSBack.setText("< Back");
        btnLSBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLSBackActionPerformed(evt);
            }
        });

        lblLSTitle.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblLSTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLSTitle.setText("Quadratic Graph Helper Steps");

        javax.swing.GroupLayout LinearStepsLayout = new javax.swing.GroupLayout(LinearSteps);
        LinearSteps.setLayout(LinearStepsLayout);
        LinearStepsLayout.setHorizontalGroup(
            LinearStepsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LinearStepsLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblLSTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                .addGap(27, 27, 27))
            .addGroup(LinearStepsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
            .addGroup(LinearStepsLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(btnLSBack, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LinearStepsLayout.setVerticalGroup(
            LinearStepsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LinearStepsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLSTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLSBack)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Quadratics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Linear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(QuadraticsCalc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(LinearCalc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(QuadraticSteps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(LinearSteps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Quadratics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Linear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(QuadraticsCalc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(LinearCalc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(QuadraticSteps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(LinearSteps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuadraticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuadraticActionPerformed
        
        //setting main panel inivisible and quadratics panel visible
        Main.setVisible(false);
        Quadratics.setVisible(true); 
        
    }//GEN-LAST:event_btnQuadraticActionPerformed

    private void btnQBackbtnQBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQBackbtnQBackActionPerformed
        
        //setting main panel visible and quadratics panel invisible
        Quadratics.setVisible(false);
        Main.setVisible(true);
    }//GEN-LAST:event_btnQBackbtnQBackActionPerformed

    private void btnLBackbtnQBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLBackbtnQBackActionPerformed
        
        //setting main panel visible and linear panel invisible
        Main.setVisible(true);
        Linear.setVisible(false); 
        
    }//GEN-LAST:event_btnLBackbtnQBackActionPerformed

    private void btnLinearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLinearActionPerformed
        
        //setting main panel invisible and linear panel visible
        Main.setVisible(false);
        Linear.setVisible(true); 
        
    }//GEN-LAST:event_btnLinearActionPerformed

    private void txtAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        
        //setting quadratics panel invisible and quadratics_calc panel visible
        Quadratics.setVisible(false); 
        QuadraticsCalc.setVisible(true); 
        
        //initializing variables from texe field input 
        double a = Double.parseDouble(this.txtA.getText()); 
        double h = Double.parseDouble(this.txtH.getText()); 
        double k = Double.parseDouble(this.txtK.getText()); 
        
        // setting arrays fro x and y coordinates 
        double[]xCord = {-2,-1,0,1,2};
        double[]yCord = {4,1,0,1,4}; 
        
        //sending information to quadcalc method
        quadCalc(a,h,k,xCord,yCord); 
        
    }//GEN-LAST:event_btnCalculateActionPerformed
    
    private void quadCalc(double a, double h,double k, double[]xCord, double[]yCord )
    {
        //loop to set x and y coordinated according to mapping notation 
        for(int i = 0; i <5; i++)
        {
            xCord[i] = xCord[i]-(-h); 
            yCord[i] = (a*(yCord[i]))+k; 
        }
        
        // setting text for equation accounding to if variables are negative or not 
        if(h < 0 && k >0 )
        {
            txaQuadCalc.setText("Equation: y = "+a+"(x+"+Math.abs(h)+")^2+"+k+"\n");
        }
        else if(k < 0 && h > 0 )
        {
            txaQuadCalc.setText("Equation: y = "+a+"(x-"+h+")^2-"+Math.abs(k)+"\n");
        }
        else if(h<0 && k<0 )
        {
            txaQuadCalc.setText("Equation: y = "+a+"(x+"+Math.abs(h)+")^2-"+Math.abs(k)+"\n");
        }
        
        
        txaQuadCalc.setText(txaQuadCalc.getText()+"\nCoordinates (x , y): \n"); 
        
        //displaying coordinates for the graph 
        for(int i = 0; i <5; i++)
        {
            txaQuadCalc.setText(txaQuadCalc.getText()+"("+xCord[i]+" , "+yCord[i]+")\n");
        }
        
        txaQuadCalc.setText(txaQuadCalc.getText()+"\nVertex: ("+xCord[2]+" , "+yCord[2]+")\n");
        
        //calculating y intercept 
        double yIntercept = (((0-(h))*(0-(h)))*a)+(k); 
        txaQuadCalc.setText(txaQuadCalc.getText()+"\nY-Intercept: (0 , "+yIntercept+")");
    }
    
    private void btnQCBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQCBackActionPerformed
        
        //removes all text from text area
        txaQuadCalc.removeAll();
        
        //setting quadratics panel visible and Quadratics_calc panel invisible
        Quadratics.setVisible(true);
        QuadraticsCalc.setVisible(false); 
    }//GEN-LAST:event_btnQCBackActionPerformed

    private void btnQCStepsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQCStepsActionPerformed
        
        //setting Quadratics_calc panel invisible and quadratics_steps panel visible
        QuadraticsCalc.setVisible(false); 
        QuadraticSteps.setVisible(true);
        
        //initializing file and buffered reader 
        FileReader read; 
        BufferedReader readQuadSteps;
        String sentence; 
		
		
	try 
	{   
            //specifying location of text file to read 
            FileReader in = new FileReader("QuadSteps.txt"); 
            readQuadSteps = new BufferedReader(in);	
            
            //loop to display each line of txt file until lins are blank 
            while ((sentence = readQuadSteps.readLine()) != null) 
            {
                txaQuadSteps.setText(txaQuadSteps.getText()+"\n"+sentence);
			    
            }
						
        }
	catch (IOException e) 
	{		
	System.out.println("Problem reading file.");
	System.err.println("IOException: " + e.getMessage());
	}
        
    }//GEN-LAST:event_btnQCStepsActionPerformed

    private void btnLCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLCalculateActionPerformed
        
        //setting linear panel invisible and linear_calc panel visible
        Linear.setVisible(false); 
        LinearCalc.setVisible(true); 
        
        //initializing variables from text field input 
        double m = Double.parseDouble(this.txtM.getText()); 
        double b = Double.parseDouble(this.txtB.getText()); 
        
        //array for x and y coordinates 
        double[]LxCord = {-2,-1,0,1,2};
        double[]LyCord = {-2,-1,0,1,2}; 
        
        //sending information to lineCalc method 
        lineCalc(m,b,LxCord,LyCord); 
                
    }//GEN-LAST:event_btnLCalculateActionPerformed
    
    private void lineCalc(double m, double b, double[]LxCord, double[]LyCord )
    {
        
        //loop to set y cordinates according to equation 
        for(int i = 0; i <5; i++)
        {
            LyCord[i] = (m*LxCord[i])+b; 
        }
        
        //displyaing equation in text area according to if number is negative or not 
        if(b < 0)
        {
            txaLineCalc.setText("Equation: y = ("+m+"*x) -"+Math.abs(b)+" \n");
        }
        else if(b > 0 )
        {
            txaLineCalc.setText("Equation: y = ("+m+"*x) +"+b+" \n");
        }
        
        txaLineCalc.setText(txaLineCalc.getText()+"\nCoordinates (x , y): \n"); 
        
        //loop to display graph coordinates 
        for(int i = 0; i <5; i++)
        {
            txaLineCalc.setText(txaLineCalc.getText()+"("+LxCord[i]+" , "+LyCord[i]+")\n");
        }
        
        txaLineCalc.setText(txaLineCalc.getText()+"\nSlope : "+m+"\n");
        
        txaLineCalc.setText(txaLineCalc.getText()+"\nY-Intercept: ("+LxCord[2]+" , "+LyCord[2]+")\n");
        
        txaLineCalc.setText(txaLineCalc.getText()+"\nX-Intercept: ("+(double)Math.round(((-b)/m)*100)*0.01+" , 0)\n");
    }
    
    private void txtMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMActionPerformed

    private void btnLCBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLCBackActionPerformed
        
        // removes all text from line_calc text area 
        txaLineCalc.removeAll();
        
        //setting Linear panel visible and linear_calc panel invisible
        Linear.setVisible(true);
        LinearCalc.setVisible(false);
    }//GEN-LAST:event_btnLCBackActionPerformed

    private void btnLCStepsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLCStepsActionPerformed
        
        //setting linear_calc panel invisible and linear_steps panel visible
        LinearCalc.setVisible(false); 
        LinearSteps.setVisible(true);
        
        //initializing file and buffered reader 
        FileReader read; 
        BufferedReader readLineSteps;
        String sentence; 
		
		
	try 
	{
            
            //stating lcation of txt file to read 
            FileReader in = new FileReader("LineSteps.txt"); 
            readLineSteps = new BufferedReader(in);	
            
            //loop to display each line of txt file until lines are blank 
            while ((sentence = readLineSteps.readLine()) != null) 
            {
                txaLineSteps.setText(txaLineSteps.getText()+"\n"+sentence);
			    
            }
						
        }
	catch (IOException e) 
	{		
	System.out.println("Problem reading file.");
	System.err.println("IOException: " + e.getMessage());
	}
        
        
    }//GEN-LAST:event_btnLCStepsActionPerformed

    private void btnLCFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLCFindActionPerformed
        
        //initialing variables from user input 
        double x = Double.parseDouble(this.txaLCX.getText());
        double m = Double.parseDouble(this.txtM.getText()); 
        double b = Double.parseDouble(this.txtB.getText());
        
        //finding y falue from x value 
        double y = (double)Math.round(((m*x)+b)*100)*0.01;
        
        this.lblLCY.setText(String.valueOf(y));
        
    }//GEN-LAST:event_btnLCFindActionPerformed

    private void btnQCFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQCFindActionPerformed
        
        //initializing variables from user input 
        double x = Double.parseDouble(this.txaQCX.getText());
        double a = Double.parseDouble(this.txtA.getText()); 
        double h = Double.parseDouble(this.txtH.getText());
        double k = Double.parseDouble(this.txtK.getText());
        
        //finding y value from x value 
        double y = (double)Math.round((a*Math.pow(x-(h),2)+k)*100)*0.01;
        
        this.lblQCY.setText(String.valueOf(y));
    }//GEN-LAST:event_btnQCFindActionPerformed

    private void btnQSBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQSBackActionPerformed
        
        //setting Quadratics_calc panel visible and quadratics_steps panel invisible
        QuadraticsCalc.setVisible(true); 
        QuadraticSteps.setVisible(false);
        
        //setting all text in text area to blank 
        txaQuadSteps.setText("");
        
    }//GEN-LAST:event_btnQSBackActionPerformed

    private void btnLSBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLSBackActionPerformed
        
        //setting linear_calc panel visible and linear_steps panel invisible
        LinearCalc.setVisible(true); 
        LinearSteps.setVisible(false);
        
        //setting all text in text area to blank 
        txaLineSteps.setText("");
        
    }//GEN-LAST:event_btnLSBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(U4_A3_Implementation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(U4_A3_Implementation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(U4_A3_Implementation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(U4_A3_Implementation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new U4_A3_Implementation().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Linear;
    private javax.swing.JPanel LinearCalc;
    private javax.swing.JPanel LinearSteps;
    private javax.swing.JPanel Main;
    private javax.swing.JPanel QuadraticSteps;
    private javax.swing.JPanel Quadratics;
    private javax.swing.JPanel QuadraticsCalc;
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnLBack;
    private javax.swing.JButton btnLCBack;
    private javax.swing.JButton btnLCFind;
    private javax.swing.JButton btnLCSteps;
    private javax.swing.JButton btnLCalculate;
    private javax.swing.JButton btnLSBack;
    private javax.swing.JButton btnLinear;
    private javax.swing.JButton btnQBack;
    private javax.swing.JButton btnQCBack;
    private javax.swing.JButton btnQCFind;
    private javax.swing.JButton btnQCSteps;
    private javax.swing.JButton btnQSBack;
    private javax.swing.JButton btnQuadratic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblLB;
    private javax.swing.JLabel lblLCTitle;
    private javax.swing.JLabel lblLCY;
    private javax.swing.JLabel lblLM;
    private javax.swing.JLabel lblLSTitle;
    private javax.swing.JLabel lblLTitle;
    private javax.swing.JLabel lblQA;
    private javax.swing.JLabel lblQCTitle;
    private javax.swing.JLabel lblQCY;
    private javax.swing.JLabel lblQH;
    private javax.swing.JLabel lblQK;
    private javax.swing.JLabel lblQSTitle;
    private javax.swing.JLabel lblQTitle;
    private javax.swing.JLabel lblStart;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txaLCX;
    private javax.swing.JTextArea txaLineCalc;
    private javax.swing.JTextArea txaLineSteps;
    private javax.swing.JTextField txaQCX;
    private javax.swing.JTextArea txaQuadCalc;
    private javax.swing.JTextArea txaQuadSteps;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtH;
    private javax.swing.JTextField txtK;
    private javax.swing.JTextField txtM;
    // End of variables declaration//GEN-END:variables
}
